networks:
  side:
    driver: overlay

services:
  proxy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:alpine
    ports:
      - "3013:3013"
    volumes:
      - ./config/data/:/data
      - ./config:/config
      - ./config/site:/srv
    networks:
      - side
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any # no always policy on swarm mode
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        reservations:
          cpus: "0.1"
          memory: 256M
        limits:
          cpus: "0.3"
          memory: 512M
    command: caddy run --config /config/Caddyfile --adapter caddyfile --watch

  tunnel:
    image: cloudflare/cloudflared:latest
    env_file: ".run.env"
    command: tunnel --no-autoupdate run
    volumes:
      - ./.run.env/:/.run.env
    networks:
      - side
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any # no always policy on swarm mode
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        reservations:
          cpus: "0.1"
          memory: 256M
        limits:
          cpus: "0.3"
          memory: 512M
