networks:
  webapp:
    driver: overlay
  common:
    driver: overlay

services:
  proxy:
    # env_file: ".run.env"
    image: ghcr.io/caddybuilds/caddy-cloudflare:alpine
    ports:
      - "3013:3013"
    volumes:
      # - ../../_volume/caddy/data/:/data
      - ./config:/config
      # - ../../_volume/caddy/site:/srv
    networks:
      - webapp
      - common
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any # no always policy on swarm mode
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        reservations:
          cpus: "0.1"
          memory: 256M
        limits:
          cpus: "0.3"
          memory: 512M
    command: caddy run --config /config/Caddyfile --adapter caddyfile --watch

  servertunnel:
    image: cloudflare/cloudflared:latest
    env_file: ".run.env"
    command: tunnel --no-autoupdate run
    volumes:
      - ./.run.env/:/.run.env
    networks:
      - webapp
      - common
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any # no always policy on swarm mode
        delay: 5s
        max_attempts: 3
        window: 60s
      resources:
        reservations:
          cpus: "0.5"
          memory: 512M
        limits:
          cpus: "1"
          memory: 1024M
